// <auto-generated />
using System;
using College.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace College.App.Migrations
{
    [DbContext(typeof(CollegeDbContext))]
    [Migration("20251020083625_updatingdefaultdata")]
    partial class updatingdefaultdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("College.App.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Colombo",
                            DOB = new DateTime(1998, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gayan@gmail.com",
                            StudentName = "Gayan Gunawardhana"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kandy",
                            DOB = new DateTime(1997, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kamal@gmail.com",
                            StudentName = "Kamal Perera"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
